name: kaggle-coronavirus-eda-forecasting
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - jupyterlab
    - pip
    - plotly
    - fbprophet
    - statsmodels
    